lambda_functions/v1/functions/lpa_codes/app/api/code_generator.py
lambda_functions/v1/functions/lpa_codes/app/api/helpers.py
lambda_functions/v1/tests/code_generator/conftest.py
lambda_functions/v1/tests/code_generator/test_generate_code.py

Super simple for now. 
Needs some more error handling, but at least it won't keep trying to generate codes indefinitely 👯‍♂️

IN-195 generate a code

---

lambda_functions/v1/functions/lpa_codes/app/api/code_generator.py
lambda_functions/v1/tests/code_generator/cases_insert_new_code.py
lambda_functions/v1/tests/code_generator/test_insert_new_code.py

No error handling, but this is the basic insert functionality

IN-197 basic insert into db

---

lambda_functions/v1/functions/lpa_codes/app/api/code_generator.py
lambda_functions/v1/functions/lpa_codes/app/api/lets_see_about_this.py
lambda_functions/v1/functions/lpa_codes/app/api/resources.py
lambda_functions/v1/tests/api/cases_handle_validate.py
lambda_functions/v1/tests/api/test_validate_handler.py

Hook up existing functions to `/validate` route
I already have the underlying logic, just tying it all together with the route.
And tests.
N/A

In 72 validate endpoint

---

docs/pull_request_template.md
lambda_functions/v1/functions/lpa_codes/app/api/lets_see_about_this.py
lambda_functions/v1/functions/lpa_codes/app/api/resources.py
lambda_functions/v1/tests/api/cases_handle_create.py
lambda_functions/v1/tests/api/cases_handle_revoke.py
lambda_functions/v1/tests/api/cases_handle_validate.py
lambda_functions/v1/tests/api/test_create_handler.py
lambda_functions/v1/tests/conftest.py

Just a couple of bits I missed yesterday:
* refactored generate test to use cases
* missing test for generating multiple codes
* revoke wasn't actually hooked into the endoint :D
* validate result matches swagger doc
Fixes
N/A
N/A

In 73 tidy up

---

docs/support_files/create_rows.json

Make sure the examples are up to date
N/A
N/A

update examples with new db fields

---

lambda_functions/v1/functions/lpa_codes/app/api/code_generator.py
lambda_functions/v1/tests/code_generator/test_generate_code.py

See IN-273, changed list of allowed characters in code

Changed list of allowed chars to new list

---

.circleci/config.yml
lambda_functions/v1/functions/lpa_codes/app/flask_lambda.py
lambda_functions/v1/functions/lpa_codes/app/lpa_codes.py

What was put down to the logging level is in fact a glaring oversight in flask lambda where by it is printing the full event to the logs. This work around will stop this from happening!

Fixsec - Fix glaring bug in the logging

---

.circleci/config.yml

fix a typo in pact tag

---

.circleci/config.yml

IN-702 upgrade terraform

---

.circleci/config.yml

upgrade to tf 0.14.11

---

.github/workflows/scanner.yml

Add action to scan repo packages

add action to scan repo

---

.circleci/config.yml
docs/ci_scripts/login_code_artifact.sh
terraform/environment/provider.tf
terraform/environment/variables.tf

Change sirius-ci to integrations-ci

IN-770 change sirius-ci to integrations-ci

---

.circleci/config.yml
terraform/environment/alerts.tf
terraform/environment/terraform.tfvars.json
terraform/environment/variables.tf

_Briefly describe the purpose of the change, and/or link to the ticket for context_

SP-824 - Remove X400 Alert #minor

---

terraform/environment/stage.tf

_Briefly describe the purpose of the change, and/or link to the ticket for context_

SP-906 - Switch API Gateway TLS to 1.2 #minor

---

.circleci/config.yml

Rather than using opg-data wrapper, which enforces unnecessary naming conventions, use Pact directly
N/A
This builds on experience we've gained by running Pact in Sirius
* N/A
* N/A
* N/A

Verify pact directly

---

docker-compose.yml
lambda_functions/v1/functions/lpa_codes/app/api/code_generator.py
lambda_functions/v1/tests/code_generator/test_generate_code.py

Reduce character set.
See UML-2050
- Apply new smaller character set to code generation and tests

UML-2050 - reduce character set for code generation

---

terraform/environment/modules/stage/stage.tf
terraform/environment/modules/stage/variables.tf
terraform/environment/stage.tf

_Briefly describe the purpose of the change, and/or link to the ticket for context_

SP-1017 - Associate WAF ACL with API Gateway Stage #minor

---

lambda_functions/v1/functions/lpa_codes/app/api/code_generator.py
lambda_functions/v1/functions/lpa_codes/app/api/endpoints.py
lambda_functions/v1/functions/lpa_codes/app/api/resources.py
lambda_functions/v1/tests/api/cases_handle_code.py
lambda_functions/v1/tests/api/test_code_handler.py
lambda_functions/v1/tests/api/test_exists_handler.py
lambda_functions/v1/tests/code_generator/cases_insert_new_code.py
lambda_functions/v1/tests/routes/conftest.py
lambda_functions/v1/tests/routes/test_code.py

Add the code function to endpoints.
Add code function, 
Change get_codes to get all fields, this will include the needed status details field
Add Tests for all of the code endpoint
Add missing test to exists endpoint
When finally finished we discovered there was an issue with Decimal() values trying to be output by jsonify, when getting items from tables in boto sometimes numbers can be converted into Decimal() see https://boto3.amazonaws.com/v1/documentation/api/latest/reference/customizations/dynamodb.html#ref-valid-dynamodb-types and https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/dynamodb.html?highlight=get_item#DynamoDB.Table.get_item
To tackle this the PR now converts expiry to a int in get_codes

add code endpoint

---

.circleci/config.yml
.pre-commit-config.yaml
.secrets.baseline
lambda_functions/v1/tests/conftest.py

fix pipeline
fixed tests. fixed docker creds.
NA

stop using specific docker login creds

---

.circleci/config.yml

Fix for a naming error on path to live.

UML-2624 fix path to live

---

.circleci/config.yml
terraform/environment/modules/lambda/lambda.tf

Naming issues with regards to log groups. Was still working but was creating an extra log group.

UML-2624c log group naming incorrect

---

.circleci/config.yml
.circleci/set_env.sh
scripts/ci_pipeline/load_testing/load_testing.go

UML-2624 fix path to live tagging

---

.circleci/config.yml
.secrets.baseline

add build image job to comit to main

UML-2624e add build image job to comit to main

---

terraform/environment/stage.tf

This part just switches API gateway over to the new image lambda

UML-2624 switch to the image

---

requirements.txt
terraform/environment/stage.tf

switch back to original lambda now it is image

UML-2624h switch back to original lambda now it is image

---

README.md
terraform/environment/lambda.tf

remove additional lambda as move complete

Uml 2624i - remove additional lambda as move complete

---

.github/workflows/sub-task-unit-tests.yml
README.md
docker-compose.yml
lambda_functions/v1/Dockerfile-Tests
lambda_functions/v1/requirements/dev-requirements.txt

_get tests working again locally_
_The bulk of this work is done in the PR https://github.com/ministryofjustice/opg-data-lpa-codes/pull/151 which renovate opened to go to pytest 8. This PR is bits and bobs left to tidy this up, including updating README_

UML-3299 get tests working again locally - bits and bobs

---

docs/expiry_dates.md

_Documentation in prep for Modernise work_
_added doc_

UML-3232 doc on expiry dates

---

.github/workflows/scheduled-destroy.yml

Update to use the moj namespaced version

Change workspace manager

---

.github/workflows/workflow-path-to-live.yml

To be deployed after production
Copying the reusable environment-deploy codeblock

Add integration deployment to path to live

---

.github/workflows/workflow-path-to-live.yml
.github/workflows/workflow-pull-request.yml

Use standard names for Github Actions Secrets

UML-3236 Use standard GHA Secret Names

---

lambda_functions/v1/functions/lpa_codes/app/api/helpers.py

Disable propagation for logger

setting propagation to false for logger

---

lambda_functions/v1/functions/lpa_codes/app/api/helpers.py

Resets the logging handlers. Needed to get around lambda using the default handler

Adding handlers reset

---

lambda_functions/v1/functions/lpa_codes/app/api/code_generator.py

_Fix issue with occasional errors when creating a new code_
_get_item has proved not to be 100% immediately reliable. So if the first get_item fails, do some retries at 0.1 sec intervals._

UML-3285 fix occasional errors from code service 

---

.pre-commit-config.yaml
.secrets.baseline

Updates detect-secret to v1.5.0

UML-4060: update detect-secrets
